cloud:
  aws:
    credentials:
      accessKey: AKIAUHYO4W7ETC6253MT
      secretKey: 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
    s3:
      bucket: dev-meeting-study-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
