cloud:
  aws:
    credentials:
      accessKey: AKIAUHYO4W7E4M6BZDPN
      secretKey: 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
    s3:
      bucket: dev-meeting-study-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
